image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      sdk install java 21.0.1 < /dev/null
      cd backend/
      mvn clean package
      cd ..
      npm install -g npm@10.2.4
      cd frontend/
      npm install --silent
      npm run build
      cd ..
      docker-compose up -d
