version: "3.8"
services:
  backend:
    container_name: backend
    image: img-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - todolist-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/todolist
  database:
    container_name: database
    image: img-database
    build:
      context: ./backend/database/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: robert
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: todolist
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - todolist-network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: img-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todolist-network

networks:
  todolist-network:
    name: todolist-network
    driver: bridge

volumes:
  db-data:
    name: volume-database
