global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'Backend ToDoList Prometheus'
  - job_name: Backend Metrics
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'Backend ToDoList Metrics'