name: Publish

on:
  pull_request:
    types: [closed]
    branches: [main]
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BASE_SEMANTIC_VERSION: ""
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 0.0.0
          MAJOR_STRING_TOKEN: major
          MINOR_STRING_TOKEN: minor
          PATCH_STRING_TOKEN: patch

      - name: Get base semantic version
        run: echo "BASE_SEMANTIC_VERSION=$(echo ${{ steps.tag_version.outputs.new_tag }})" >> $GITHUB_ENV

      - name: Check if new tag was created
        id: check_tag
        run: |
          if [ "${{ steps.tag_version.outputs.new_tag }}" != "" ]; then
            echo "new_tag_created=true" >> $GITHUB_OUTPUT
          else
            echo "new_tag_created=false" >> $GITHUB_OUTPUT
          fi

      - name: Create a GitHub release
        if: steps.check_tag.outputs.new_tag_created == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.BASE_SEMANTIC_VERSION }}
          name: Release ${{ env.BASE_SEMANTIC_VERSION }}
          skipIfReleaseExists: true
      - name: Login to Docker Hub
        if: steps.check_tag.outputs.new_tag_created == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Docker meta for backend
        if: steps.check_tag.outputs.new_tag_created == 'true'
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: |
            rofeit00/todo-backend
          tags: |
            type=raw,value=${{ env.BASE_SEMANTIC_VERSION }}

      - name: Docker meta for frontend
        if: steps.check_tag.outputs.new_tag_created == 'true'
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: |
            rofeit00/todo-frontend
          tags: |
            type=raw,value=${{ env.BASE_SEMANTIC_VERSION }}

      - name: Build and push backend
        if: steps.check_tag.outputs.new_tag_created == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ steps.meta_backend.outputs.tags }}
            rofeit00/todo-backend:latest

      - name: Build and push frontend
        if: steps.check_tag.outputs.new_tag_created == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ steps.meta_frontend.outputs.tags }}
            rofeit00/todo-frontend:latest
